'use client';

import Link from 'next/link';
import dynamic from 'next/dynamic';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight } from 'lucide-react';

import ImageCard from '../../components/ImageCard';
import { getLatestJobs } from '../../lib/api';
import type { LatestJob } from '../../types/image-job';

const ImageCardModal = dynamic(() => import('../../components/ImageCardModal'), {
  ssr: false,
});

export default function ClientGallery() {
  const [jobs, setJobs] = useState<LatestJob[]>([]);
  const [loading, setLoading] = useState(true);
  const [modalOpen, setModalOpen] = useState(false);
  const [selected, setSelected] = useState<{ id: string; url: string } | null>(null);

  useEffect(() => {
    let ignore = false;
    (async () => {
      try {
        const latest = await getLatestJobs();
        if (!ignore) setJobs(latest.filter(job => job.imageUrl));
      } catch {
        if (!ignore) setJobs([]);
      } finally {
        if (!ignore) setLoading(false);
      }
    })();

    return () => {
      ignore = true;
    };
  }, []);

  const placeholders = useMemo(() => Array.from({ length: 10 }), []);
  const heroPlaceholders = useMemo(() => Array.from({ length: 6 }), []);
  const heroShowcase = useMemo(() => jobs.slice(0, 6), [jobs]);

  return (
    <>
      <section className="space-y-6">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <h2 className="text-3xl font-semibold text-white sm:text-4xl">Latest imagino.AI creations</h2>
            <p className="text-sm text-gray-400 sm:text-base">
              Fresh work generated by our community, updated moments after they finish rendering.
            </p>
          </div>
          <Link
            href="#community-gallery"
            className="inline-flex items-center justify-center rounded-full border border-white/10 bg-white/5 px-5 py-2 text-sm font-medium text-gray-100 transition hover:bg-white/10"
          >
            View full gallery
            <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {loading || heroShowcase.length === 0
            ? heroPlaceholders.map((_, i) => (
                <div key={`hero-placeholder-${i}`} className="break-inside-avoid">
                  <ImageCard loading onClick={() => {}} />
                </div>
              ))
            : heroShowcase.map(job => (
                <div key={`hero-${job.id}`} className="break-inside-avoid">
                  <ImageCard
                    src={job.imageUrl}
                    jobId={job.id}
                    onClick={() => {
                      setSelected({ id: job.id, url: job.imageUrl });
                      setModalOpen(true);
                    }}
                  />
                </div>
              ))}
        </div>
      </section>

      <section id="community-gallery" className="space-y-8">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <h2 className="text-3xl font-semibold text-white sm:text-4xl">Community showcase</h2>
            <p className="text-sm text-gray-400 sm:text-base">
              Explore standout projects from artists and teams building with imagino.AI every single day.
            </p>
          </div>
          <Link
            href="/images/replicate"
            className="inline-flex items-center justify-center rounded-full border border-white/10 bg-white/5 px-5 py-2 text-sm font-medium text-gray-100 transition hover:bg-white/10"
          >
            Browse entire library
            <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
        </div>

        <div className="columns-1 gap-5 sm:columns-2 md:columns-3 lg:columns-4 [column-fill:_balance]">
          {loading
            ? placeholders.map((_, i) => (
                <div key={`placeholder-${i}`} className="mb-5 break-inside-avoid">
                  <ImageCard loading onClick={() => {}} />
                </div>
              ))
            : jobs.map(job => (
                <div key={job.id} className="mb-5 break-inside-avoid">
                  <ImageCard
                    src={job.imageUrl}
                    jobId={job.id}
                    onClick={() => {
                      setSelected({ id: job.id, url: job.imageUrl });
                      setModalOpen(true);
                    }}
                  />
                </div>
              ))}
        </div>
      </section>

      <ImageCardModal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        jobId={selected?.id ?? null}
        fallbackUrl={selected?.url}
      />
    </>
  );
}
